django/materials/materials/apps/core/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'materials.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', 'materials.apps.core.views.index', name='index'),
)

django/materials/materials/apps/loginsys/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'materials.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^register/$', 'materials.apps.loginsys.views.register', name='register'),
    url(r'^login/$', 'materials.apps.loginsys.views.login', name='login'),
    url(r'^logout/$', 'materials.apps.loginsys.views.logout', name='logout'),
)

django/materials/materials/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'materials.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^auth/', include('materials.apps.loginsys.urls', namespace='loginsys')),
    url(r'^$', include('materials.apps.core.urls', namespace='index')),
)

django/materials/materials/apps/core/models.py
from django.db import models

# Create your models here.

django/materials/materials/apps/loginsys/models.py
from django.db import models

# Create your models here.

django/materials/materials/apps/loginsys/forms.py
from django.forms import ModelForm
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class userform(UserCreationForm):
    email = forms.EmailField(max_length=30, label='электронная почта')

    class Meta:
        model = User
        fields = ("username", "email",)

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])

        if commit:
            user.save()
        return user

class userlightform(forms.Form):
    username = forms.CharField(max_length=50, label='Имя пользователя')
    email = forms.EmailField(label='Почта')
    password1 = forms.CharField(max_length=15, label='Пароль', widget=forms.PasswordInput, help_text='Введите пороль')
    password2 = forms.CharField(max_length=15, label='Подтверждение пароля', widget=forms.PasswordInput, help_text='Подтверждение пароля')

django/materials/materials/apps/core/views.py
from django.shortcuts import render_to_response
from django.core.context_processors import csrf
from django.contrib import auth

def index(request):
    value = {}
    value.update(csrf(request))
    value['user'] = auth.get_user(request)
    return render_to_response('index.html', value)

django/materials/materials/apps/loginsys/views.py
from django.shortcuts import render_to_response
from django.core.context_processors import csrf
from django.contrib import auth
from django.contrib.auth.forms import User
from materials.apps.loginsys.forms import userform, userlightform
from django.contrib.auth.forms import UserCreationForm

def register(request):
    value = {}
    value.update(csrf(request))
    value['user'] = auth.get_user(request)
    value['form'] = userlightform
    if request.POST:
        new_user = userlightform(request.POST)
        if new_user.is_valid():
            username = request.POST['username']
            #email = request.POST['email']
            password1 = request.POST['password1']
            password2 = request.POST['password2']
            user = User
            email = user.objects.normalize_email(request.POST['email'])

    return render_to_response('register.html', value)

def login(request):
    pass

def logout(request):
    pass

django/materials/materials/apps/loginsys/templates/register.html
{% extends 'index.html' %}

{% block register %}

    <form action="" method="post">
        {% csrf_token %}
        <div>
            <div class="medium-3 columns">{{ form.username.label }}</div>
            <div class="medium-4 columns">{{ form.username }}</div>
            <div class="medium-5 columns">{{ form.username.help_text }}</div>
        </div>
        <div class="medium-offset-3"><input class="button" type="submit"></div>
    </form>


    {{ form }}
{% endblock %}

django/materials/materials/templates/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Библиотека технической документации</title>
    <link rel="stylesheet" type="text/css" href="{% static "Foundation/css/foundation.css" %}">
</head>
<body>
<div class="top-bar">
    <section class="top-bar-section">
        <ul class="right">
            {% if user.is_anonymous  %}:
                <li>
                    <form action="{% url 'loginsys:register' %}" method="post">
                        {% csrf_token %}
                        <li><input type="text" name="username"  placeholder="Имя пользователя"></li>
                        <li><input type="text" name="password" placeholder="Пароль"></li>
                        <li><input class="button" type="submit" style="width: 90px" value="Войти"></li>
                        <li><input class="button" type="submit" style="width: 90px" value="Регистрация"></li>
                    </form>
                </li>
            {% else %}
                <li><a href="">({{ user.username }}) Выйти</a> </li>
            {% endif %}
        </ul>
    </section>
</div>

<div class="row">
    <h3><a href="{% url 'index:index' %}">Библиотека технической документации</a> </h3>
</div>

<div class="row">{% block register %}{% endblock %}</div>

</body>
</html>